services:
  antizapret-vpn:
    image: xtrime/antizapret-vpn:latest
    build: ./
    container_name: antizapret-vpn
    restart: unless-stopped
    ports:
      - "1194:1194/tcp"
      - "1194:1194/udp"
    volumes:
      - ./client_keys/:/root/easy-rsa-ipsec/CLIENT_KEY/
      - ./easyrsa3/:/root/easy-rsa-ipsec/easyrsa3/
      - ./result/:/root/antizapret/result/
      - ./temp/:/root/antizapret/temp/
      # Some domains blocked unofficially: https://ntc.party/t/vpn/129/127
      - ./config/include-hosts-custom.txt:/root/antizapret/config/include-hosts-custom.txt
      - ./config/exclude-hosts-custom.txt:/root/antizapret/config/exclude-hosts-custom.txt
      - ./config/exclude-hosts-dist.txt:/root/antizapret/config/exclude-hosts-dist.txt
      - ./config/include-ips-custom.txt:/root/antizapret/config/include-ips-custom.txt
      - ./config/exclude-ips-custom.txt:/root/antizapret/config/exclude-ips-custom.txt
    privileged: true
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "1"
